name: inv-mgmt

services:
  # reference: https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
  db:
    image: mysql:lts
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - .mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # initialisation
    env_file: 
      - .env
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  mysql_data: